# ------- Branding Related Config ------- #
- name: INSTALLATION_NAME
  value: 'Chatwoot'
- name: LOGO_THUMBNAIL
  value: '/brand-assets/logo_thumbnail.svg'
- name: LOGO
  value: '/brand-assets/logo.svg'
- name: LOGO_DARK
  value: '/brand-assets/logo_dark.svg'
- name: BRAND_URL
  value: 'https://prograpps.com/multiagente'
- name: WIDGET_BRAND_URL
  value: 'https://prograpps.com'
- name: BRAND_NAME
  value: 'MultiAgente MibOT'
- name: TERMS_URL
  value: 'https://prograpps.com/terminos-servicio'
- name: PRIVACY_URL
  value: 'https://prograpps.com/politica-privacidad'
- name: DISPLAY_MANIFEST
  value: true
# ------- End of Branding Related Config ------- #
